version: '3.7'
services:
  terraform:
    container_name: sec-hub-hello-world-lambda-terraform
    build: "./images/terraform"
    volumes:
      - '.:/app'
    environment:
      - TF_VAR_localstack_url=http://localstack:4566
