version: '3.7'
services:
  terraform:
    container_name: sec-hub-hello-world-lambda-terraform
    build: "./images/terraform"
    volumes:
      - '.:/app'
    environment:
      - TF_VAR_localstack_url=http://localstack:4566
  localstack:
    container_name: sec-hub-hello-world-lambda-localstack
    image: localstack/localstack:0.12.7
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=apigateway,serverless
      - DEFAULT_REGION=eu-west-1
      - AWS_DEFAULT_REGION=eu-west-1
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOSTNAME_EXTERNAL=localstack
      - HOSTNAME=localstack
      - USE_SSL=false
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
